ecomapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name='ecomapp'
urlpatterns=[
    # store------------------
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('contact-us/',ContactView.as_view(),name='contact'),
    path('all-products/',AllProductsView.as_view(),name='allproducts'),
    path('product/<slug:slug>/',ProductDetailView.as_view(),name='productdetail'),
    path('my-cart/',MyCartView.as_view(),name='mycart'),
    path('wish-list/',WishListView.as_view(),name='wishlist'),
    path('filter-product/',views.filter_product,name='filter-product'),
    
    path('add-to-cart-<int:pro_id>/',AddToCartView.as_view(),name='addtocart'),
    path('manage-cart/<int:cp_id>/',ManageCartView.as_view(),name='managecart'),
    path('empty-cart/',EmptyCartView.as_view(),name='emptycart'),
    path('add-to-wishlist-<int:pro_id>/',AddToWishListView.as_view(),name='addtowishlist'),
    path('remove-from-wishlist-<int:wli_id>/',RemoveFromWishListView.as_view(),name='removefromwishlist'),
    path('search/',SearchView.as_view(),name='search'),
# profile
    path('checkout/',CheckoutView.as_view(),name='checkout'),
    path('register/',CustomerRegistrationView.as_view(),name='customerRegistration'),
    path('logout/',CustomerLogoutView.as_view(),name='customerlogout'),
    path('login/',CustomerLoginView.as_view(),name='customerlogin'),
    path('profile/',CustomerProfileView.as_view(),name='customerprofile'),
    path('profile/order-<int:pk>/',CustomerOrderDetailView.as_view(),name='customerorderdetail'),
    path('forgot-password/',PasswordForgotView.as_view(),name='passwordforgot'),
    path('password-reset/<email>/<token>/',PasswordResetView.as_view(),name='passwordreset'),

# admin------------
    path('admin-login/',AdminLoginView.as_view(),name='adminlogin'),
    path('admin-home/',AdminHomeView.as_view(),name='adminhome'),
    path('admin-order-<int:pk>/',AdminOrderDetailView.as_view(),name='adminorderdetail'),
    path('admin-logout/',AdminLogoutView.as_view(),name='adminlogout'),
    path('admin-order-list/',AdminOrderListView.as_view(),name='adminorderlist'),
    path('admin-order-<int:pk>-change/',AdminOrderStatusChangeView.as_view(),name='adminorderstatuschange'),

    path('admin-order-received/',AdminOrderReceivedView.as_view(),name='adminorderreceived'),
    path('admin-order-processing/',AdminOrderProcessingView.as_view(),name='adminorderprocessing'),
    path('admin-order-on-delivery/',AdminOrderOnDeliveryView.as_view(),name='adminorderondelivery'),
    path('admin-order-completed/',AdminOrderCompletedView.as_view(),name='adminordercompleted'),
    path('admin-order-canceled/',AdminOrderCanceledView.as_view(),name='adminordercanceled'),

    path('admin-delete-order<int:pk>/',AdminDeleteOrderView.as_view(),name='admindeleteorder'),
    path('admin-product/list/',AdminProductListView.as_view(),name='adminproductlist'),
    path('admin-product/add/',AdminProductCreateView.as_view(),name='adminproductcreate'),
    path('admin-product/delete/<int:pk>',AdminProductDeleteView.as_view(),name='adminproductdelete'),

]

ecomproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecomapp.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=50)
    image=models.ImageField(upload_to='admins_avatar')
    mobile=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username



class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200)
    address=models.CharField(max_length=200,null=True,blank=True)
    joined_on=models.DateTimeField(auto_now_add=True)
    avatar=models.ImageField(upload_to='customer_avatar',blank=True,null=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.title+ '___#'+ str(self.id)
    
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    thumbnail=models.ImageField(upload_to='products/thumbnails')
    marked_price=models.BigIntegerField()
    selling_price=models.BigIntegerField()
    description=models.TextField(blank=True)  
    view_count=models.BigIntegerField(default=0)
    sex=models.BooleanField(blank=True,default=False)
    line=models.CharField(null=True,blank=True,max_length=200)
    

    def __str__(self):
        return self.title + '___#'+ str(self.id)
    
class ProductSize(models.Model):
    product=models.OneToOneField(Product,on_delete=models.CASCADE)
    size_6=models.BooleanField(blank=True)
    size_6h=models.BooleanField(blank=True)
    size_7=models.BooleanField(blank=True)
    size_7h=models.BooleanField(blank=True)
    size_8=models.BooleanField(blank=True)
    size_8h=models.BooleanField(blank=True)
    size_9=models.BooleanField(blank=True)
    size_9h=models.BooleanField(blank=True)
    size_10=models.BooleanField(blank=True)
    size_10h=models.BooleanField(blank=True)
    size_11=models.BooleanField(blank=True)
    size_S=models.BooleanField(blank=True,default=False)
    size_M=models.BooleanField(blank=True,default=False)   
    size_L=models.BooleanField(blank=True,default=False)   
    size_XL=models.BooleanField(blank=True,default=False)   
    size_XXL=models.BooleanField(blank=True,default=False)   

    
    def __str__(self):
        return self.product.title

class WishList(models.Model):
    customer=models.OneToOneField(Customer,on_delete=models.CASCADE,null=True,blank=True)
    count=models.IntegerField(null=True,blank=True)

    def __str__(self):      
        return 'wishlist :'+str(self.id)    
        
class WishListItem(models.Model):
    wishlist=models.ForeignKey(WishList,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    def __str__(self):
        return  'wish list : '+str(self.wishlist.id) + 'wish_list_item :'+str(self.id)
class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='products/images/')

    def __str__(self):
        return self.product.title
    
class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    total=models.BigIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    count=models.IntegerField(null=True,blank=True)

    def __str__(self):
        return 'cart :'+str(self.id)
        # return str(self.id)
    
class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.BigIntegerField()
    quantity=models.BigIntegerField()
    subtotal=models.BigIntegerField()
    size=models.CharField(null=True,blank=True,max_length=10)
    sex=models.CharField(max_length=10,blank=True,null=True)


    def __str__(self):
        return 'Cart: '+str(self.cart.id) + 'CartProduct: '+str(self.id)
    
ORDER_STATUS=(
    ('Order received','Order received'),
    ('Order processing','Order processing'),        
    ('On delivery','On delivery'),
    ('Order completed','Order completed'),
    ('Order canceled','Order canceled'),

)
    
class Order(models.Model):
    cart=models.OneToOneField(Cart,on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile=models.CharField(max_length=12)
    email=models.EmailField(null=True,blank=True)
    # subtotal=models.BigIntegerField()
    discount=models.BigIntegerField()
    total=models.BigIntegerField()
    order_status=models.CharField(max_length=50,choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Order : ' +str(self.id)

templates/adminpages/adminhome.html
{% extends 'adminpages/adminbase.html' %}
{% load  humanize %}
{% block title %}Admin Home {% endblock %}

{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary active' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container " >
    <div class="row  admin-card-white card-border " >
        <div class="col-md-12  " >
            <h3>Unprocessed Orders</h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in unprocessedorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock content  %}

templates/adminpages/adminlogin.html
{% extends 'base.html' %}
{% block title %}Admin Login{% endblock title %}
{%  block content %}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <div class="row ">
        <div class="col-md-6 mx-auto  admin-login-form" >
            <h3>Admin Login Form</h3><hr>
            <form action="" method="POST" >
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" >Login as a admin</button>
                {% if error1 %}
                <li style="color:red;" >{{error1}}</li>
                {% endif  %}
            </form>
        </div>

    </div>

</div>

{% endblock content %}

templates/adminpages/adminordercanceled.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %} admin order canceled {% endblock title %}
{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger active' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container" >
    <div class="row  admin-card-white card-border" >
        <div class="col-md-12" >
            <h3>Canceled Orders</h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in canceled_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock content %}

templates/adminpages/adminordercompleted.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %} admin order completed {% endblock title %}
{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success active' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container" >
    <div class="row  admin-card-white card-border" >
        <div class="col-md-12" >
            <h3>Completed Orders</h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in completed_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>  
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock content %}

templates/adminpages/adminorderdetail.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %} Order detail {% endblock title %}
{% block content %}

<div class="container mt-2" >
    <a class='btn btn-outline-primary ' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>
</div>



<div class="container" >
    <div class="row  admin-card-white card-border py-3 mt-3" >
        <div class="col-md-8 mx-auto" >
            <h3>Order Detail</h3><hr>
            <p> <span class="font-weight-bold">Order ID :</span> #ORDER_{{order_obj.id}}</p>
            {% if order_obj.order_status == 'Order canceled' %}
            <p> <span class="font-weight-bold ">Order Status :</span> <span class="text-danger font-weight-bold" > {{order_obj.order_status}} </span> </p>
            {% else %}
            <p> <span class="font-weight-bold ">Order Status :</span> <span class="text-success font-weight-bold " > {{order_obj.order_status}} </span> </p>
            {% endif %}
            <p> <span class="font-weight-bold">Order on :</span> {{order_obj.created_at}}({{order_obj.created_at|timesince}} ago)</p>
            <p> <span class="font-weight-bold">Customer name: </span> {{order_obj.ordered_by}}</p>
            <p> <span class="font-weight-bold">Customer mobile :</span>  {{order_obj.mobile}}</p>
            <p> <span class="font-weight-bold">Shipping Address :</span> {{order_obj.shipping_address}}</p>
            <p> <span class="font-weight-bold">Email :</span> {{order_obj.email}}</p>

            <h4>Ordered Items</h4>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Item</th>
                        <th>Image</th>
                        <th>Size</th>
                        <th>Sex</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in order_obj.cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:productdetail' cp.product.slug %}" > {{cp.product.title}}   </a> </td>
                        <td><img class="img-fluid" style="width:100px;" src="{{cp.product.thumbnail.url}}" alt=""></td>
                        <td>{{cp.size}} (US)</td>
                        {% if cp.sex == 'True' %}
                        <td>Nam</td>
                        {%  else %}
                        <td>Nữ</td>
                        {% endif %}
                        <td>{{cp.rate|intcomma}} đ</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal|intcomma}} đ </td>
                    {% endfor %}    
                    </tr>
                    <tr>
                        <th colspan="7" class=" text-right" >Total:</th>
                        <th >{{order_obj.total|intcomma}} đ</th>
                    </tr>
                </tbody>
            </table>
            <form  id="form" action="{% url 'ecomapp:adminorderstatuschange' order_obj.id %}"  method="POST">
                {% csrf_token %}
                <select id="status"  name="status"  class="btn btn-secondary" >
                    {% for i,j in allstatus %}  
                    <option value="{{i}}" {% if i == order_obj.order_status %}selected{% endif %} >{{j}}</option>              
                    {% endfor %}
                </select>
                <button id="submit" class="btn  btn-primary" type="submit">Update</button>
            </form>
        </div>

    </div>

</div>

<script>
    let status= document.getElementById('status').addEventListener('onchange',function(){
        document.getElementById('form').submit()
    })
</script>

{% endblock content %}


templates/adminpages/adminorderlist.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %}All orders{% endblock %}
{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary active' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container" >
    <div class="row  admin-card-white card-border" >
        <div class="col-md-12" >
            <h3>All orders </h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in allorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        {% if order.order_status == 'Order canceled' %}
                        <td class="text-danger font-weight-bold " >{{order.order_status}}</td>
                        {% else  %}
                        <td class="text-success font-weight-bold " >{{order.order_status}}</td>
                        {%  endif %}
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

</div>
{% endblock content %}

templates/adminpages/adminorderondelivery.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %} admin order on-delivery {% endblock title %}
{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary active' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container" >
    <div class="row  admin-card-white card-border" >
        <div class="col-md-12" >
            <h3>On-Delivery Orders</h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in on_delivery_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock content %}

templates/adminpages/adminorderprocessing.html
{% extends 'adminpages/adminbase.html' %}
{% load humanize %}
{% block title %} admin order processing {% endblock title %}
{% block content %}
<div class="container mt-2" >
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminhome' %}">Home</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderlist' %}">All Orders</a> 
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderreceived' %}">Received Orders</a>
    <a class='btn btn-outline-primary active' href="{% url 'ecomapp:adminorderprocessing' %}">Processing Orders</a>
    <a class='btn btn-outline-primary' href="{% url 'ecomapp:adminorderondelivery' %}">On delivery Orders</a>
    <a class='btn btn-outline-success' href="{% url 'ecomapp:adminordercompleted' %}">Completed Orders</a>
    <a class='btn btn-outline-danger' href="{% url 'ecomapp:adminordercanceled' %}">Canceled Orders</a>

    
    <a href="{% url 'ecomapp:adminlogout' %}" class="float-right btn btn-danger " >Log out </a>

    
</div>
<div class="container" >
    <div class="row  admin-card-white card-border" >
        <div class="col-md-12" >
            <h3>Processing Orders</h3>
            <table class="table" >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Order ID</th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in processing_orders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td> <a href="{% url 'ecomapp:adminorderdetail'  order.id %}" >  #ORDER_{{order.id}} </a>  </td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}} ({{order.created_at|timesince}})</td>
                        <td>{{order.total|intcomma}} đ</td>
                        <td> <a href="{% url 'ecomapp:admindeleteorder'  order.id %}"  class="btn btn-block btn-outline-secondary">x</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
</div>

{% endblock content %}