ecomapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name='ecomapp'
urlpatterns=[
    # store------------------
    path('',HomeView.as_view(),name='home'),
    path('about/',AboutView.as_view(),name='about'),
    path('contact-us/',ContactView.as_view(),name='contact'),
    path('all-products/',AllProductsView.as_view(),name='allproducts'),
    path('product/<slug:slug>/',ProductDetailView.as_view(),name='productdetail'),
    path('my-cart/',MyCartView.as_view(),name='mycart'),
    path('wish-list/',WishListView.as_view(),name='wishlist'),
    path('filter-product/',views.filter_product,name='filter-product'),
    
    path('add-to-cart-<int:pro_id>/',AddToCartView.as_view(),name='addtocart'),
    path('manage-cart/<int:cp_id>/',ManageCartView.as_view(),name='managecart'),
    path('empty-cart/',EmptyCartView.as_view(),name='emptycart'),
    path('add-to-wishlist-<int:pro_id>/',AddToWishListView.as_view(),name='addtowishlist'),
    path('remove-from-wishlist-<int:wli_id>/',RemoveFromWishListView.as_view(),name='removefromwishlist'),
    path('search/',SearchView.as_view(),name='search'),
# profile
    path('checkout/',CheckoutView.as_view(),name='checkout'),
    path('register/',CustomerRegistrationView.as_view(),name='customerRegistration'),
    path('logout/',CustomerLogoutView.as_view(),name='customerlogout'),
    path('login/',CustomerLoginView.as_view(),name='customerlogin'),
    path('profile/',CustomerProfileView.as_view(),name='customerprofile'),
    path('profile/order-<int:pk>/',CustomerOrderDetailView.as_view(),name='customerorderdetail'),
    path('forgot-password/',PasswordForgotView.as_view(),name='passwordforgot'),
    path('password-reset/<email>/<token>/',PasswordResetView.as_view(),name='passwordreset'),

# admin------------
    path('admin-login/',AdminLoginView.as_view(),name='adminlogin'),
    path('admin-home/',AdminHomeView.as_view(),name='adminhome'),
    path('admin-order-<int:pk>/',AdminOrderDetailView.as_view(),name='adminorderdetail'),
    path('admin-logout/',AdminLogoutView.as_view(),name='adminlogout'),
    path('admin-order-list/',AdminOrderListView.as_view(),name='adminorderlist'),
    path('admin-order-<int:pk>-change/',AdminOrderStatusChangeView.as_view(),name='adminorderstatuschange'),

    path('admin-order-received/',AdminOrderReceivedView.as_view(),name='adminorderreceived'),
    path('admin-order-processing/',AdminOrderProcessingView.as_view(),name='adminorderprocessing'),
    path('admin-order-on-delivery/',AdminOrderOnDeliveryView.as_view(),name='adminorderondelivery'),
    path('admin-order-completed/',AdminOrderCompletedView.as_view(),name='adminordercompleted'),
    path('admin-order-canceled/',AdminOrderCanceledView.as_view(),name='adminordercanceled'),

    path('admin-delete-order<int:pk>/',AdminDeleteOrderView.as_view(),name='admindeleteorder'),
    path('admin-product/list/',AdminProductListView.as_view(),name='adminproductlist'),
    path('admin-product/add/',AdminProductCreateView.as_view(),name='adminproductcreate'),
    path('admin-product/delete/<int:pk>',AdminProductDeleteView.as_view(),name='adminproductdelete'),

]

ecomproject/urls.py

from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecomapp.urls')),
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Admin(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=50)
    image=models.ImageField(upload_to='admins_avatar')
    mobile=models.CharField(max_length=20)

    def __str__(self):
        return self.user.username



class Customer(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    full_name=models.CharField(max_length=200)
    address=models.CharField(max_length=200,null=True,blank=True)
    joined_on=models.DateTimeField(auto_now_add=True)
    avatar=models.ImageField(upload_to='customer_avatar',blank=True,null=True)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)

    def __str__(self):
        return self.title+ '___#'+ str(self.id)
    
class Product(models.Model):
    title=models.CharField(max_length=200)
    slug=models.SlugField(unique=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    thumbnail=models.ImageField(upload_to='products/thumbnails')
    marked_price=models.BigIntegerField()
    selling_price=models.BigIntegerField()
    description=models.TextField(blank=True)  
    view_count=models.BigIntegerField(default=0)
    sex=models.BooleanField(blank=True,default=False)
    line=models.CharField(null=True,blank=True,max_length=200)
    

    def __str__(self):
        return self.title + '___#'+ str(self.id)
    
class ProductSize(models.Model):
    product=models.OneToOneField(Product,on_delete=models.CASCADE)
    size_6=models.BooleanField(blank=True)
    size_6h=models.BooleanField(blank=True)
    size_7=models.BooleanField(blank=True)
    size_7h=models.BooleanField(blank=True)
    size_8=models.BooleanField(blank=True)
    size_8h=models.BooleanField(blank=True)
    size_9=models.BooleanField(blank=True)
    size_9h=models.BooleanField(blank=True)
    size_10=models.BooleanField(blank=True)
    size_10h=models.BooleanField(blank=True)
    size_11=models.BooleanField(blank=True)
    size_S=models.BooleanField(blank=True,default=False)
    size_M=models.BooleanField(blank=True,default=False)   
    size_L=models.BooleanField(blank=True,default=False)   
    size_XL=models.BooleanField(blank=True,default=False)   
    size_XXL=models.BooleanField(blank=True,default=False)   

    
    def __str__(self):
        return self.product.title

class WishList(models.Model):
    customer=models.OneToOneField(Customer,on_delete=models.CASCADE,null=True,blank=True)
    count=models.IntegerField(null=True,blank=True)

    def __str__(self):      
        return 'wishlist :'+str(self.id)    
        
class WishListItem(models.Model):
    wishlist=models.ForeignKey(WishList,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)

    def __str__(self):
        return  'wish list : '+str(self.wishlist.id) + 'wish_list_item :'+str(self.id)
class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='products/images/')

    def __str__(self):
        return self.product.title
    
class Cart(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.SET_NULL,blank=True,null=True)
    total=models.BigIntegerField(default=0)
    created_at=models.DateTimeField(auto_now_add=True)
    count=models.IntegerField(null=True,blank=True)

    def __str__(self):
        return 'cart :'+str(self.id)
        # return str(self.id)
    
class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.BigIntegerField()
    quantity=models.BigIntegerField()
    subtotal=models.BigIntegerField()
    size=models.CharField(null=True,blank=True,max_length=10)
    sex=models.CharField(max_length=10,blank=True,null=True)


    def __str__(self):
        return 'Cart: '+str(self.cart.id) + 'CartProduct: '+str(self.id)
    
ORDER_STATUS=(
    ('Order received','Order received'),
    ('Order processing','Order processing'),        
    ('On delivery','On delivery'),
    ('Order completed','Order completed'),
    ('Order canceled','Order canceled'),

)
    
class Order(models.Model):
    cart=models.OneToOneField(Cart,on_delete=models.CASCADE)
    ordered_by=models.CharField(max_length=200)
    shipping_address=models.CharField(max_length=200)
    mobile=models.CharField(max_length=12)
    email=models.EmailField(null=True,blank=True)
    # subtotal=models.BigIntegerField()
    discount=models.BigIntegerField()
    total=models.BigIntegerField()
    order_status=models.CharField(max_length=50,choices=ORDER_STATUS)
    created_at=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Order : ' +str(self.id)

templates/addtocart.html
{% extends 'base.html' %}

{% block title %} Add to cart {% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successsfully</h3>
</div>
{% endblock %}

templates/allproducts.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block title %}
All products
{% endblock title %}

{% block content %}
<div class="container">
    <h3>Categories</h3><br><br>
    {%  for cat in allcategories %}
    <h4>{{cat.title}}</h4>
    <hr>
    <div class="row mt-20" >
        {% for p in cat.product_set.all %}
        <div class=" col-md-3 card ">
            <h5 class="mt-3 text-center " >{{p.title}}</h5>
            <h5 class="text-center " >
                {% if p.sex == True %}
                <p>Nam</p>
                {% else  %}
                <p>Nữ</p>
                {% endif %}
            </h5>
            <div class="home-product-price">
                <a href="{% url 'ecomapp:productdetail' p.slug %}"><img class="img-fluid"  src="{{p.thumbnail.url}}" alt="" width="250" ></a>
                <span><strong> Price </strong> <small> <strike>{{p.marked_price|intcomma}}</strike> </small> <strong> {{p.selling_price|intcomma}} đ </span></strong>

                {%  if p in product_in_wishlist %}
                <a class=" inline-block add-to-wishlist " >
                    <img class="heart-icon-navbar "  src="{% static 'icon/red-heart-icon.png' %}" alt="add to wishlist">
                </a>
                {% else %}
                <a href="{% url 'ecomapp:addtowishlist'  p.id %}" class="inline-block add-to-wishlist ">
                    <img class="heart-icon-navbar "  src="{% static 'icon/black-heart-icon.png' %}" alt="">
                </a>
                {%  endif %}

            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{%  endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}  {% endblock %}  </title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}" type="text/css" >
    
</head>
<!-- header -->
<header >
    <div class="container  " >
        <a href="{% url 'ecomapp:home' %}"  class="text-white "><img style="width:30px;" src="{% static 'images/logo-asics.png' %}" alt=""> <strong class >ASICS </strong> </a>
        <a href="{% url 'ecomapp:about'  %}" class="text-white ml-2">About us </a>
        <a href="{% url 'ecomapp:contact' %}"class="text-white ml-2">Contact us </a>
        <!-- <a href="{% url 'ecomapp:allproducts' %}"class="text-white ml-2">Categories </a> -->
        {% if cart.count %}
        <a href="{% url 'ecomapp:mycart' %}"class="ml-2"> 
            <span>
                <img  style="width:35px;" src="{% static 'icon/cart-icon.png' %}" alt=""> 
                <span class="cart-count" >{{cart.count}}</span> 
            </span>
        </a>
        {% else %}
        <a href="{% url 'ecomapp:mycart' %}"class="ml-2"> 
            <span>
                <img  style="width:35px;" src="{% static 'icon/cart-icon.png' %}" alt=""> 
            </span>
        </a>
        {% endif %}


        {% if wishlist.count  %}
        <a href="{% url 'ecomapp:wishlist' %}"class="ml-4  "> 
            <span>
                <img  style="width:30px;"  src="{% static 'icon/white-heart-icon.png' %}" alt="">
                <span class="wishlist-count " >{{wishlist.count}}</span>
            </span>
        </a>
        {% else %}
        <a href="{% url 'ecomapp:wishlist' %}"class="ml-4  "> 
            <span>
                <img  style="width:30px;"  src="{% static 'icon/white-heart-icon.png' %}" alt="">  
            </span>
        </a>
        {% endif %}
        
        {% if request.user.customer %}
        <a href="{% url 'ecomapp:customerlogout' %}" class="mt-1 btn btn-danger opacity-2 float-right ml-2  " >Log out</a>
        <a href="{% url 'ecomapp:customerprofile' %}" class="mt-1  btn btn-outline-light float-right rounded " >My profile</a>
        <img class="img-fluid avatar float-right  mr-2 mt-1" src="{{request.user.customer.avatar.url}}" alt="">
        <p class="float-right text-white mr-3" >Xin chào {{request.user.customer}} ! </p>
        {%  else %}
        <a href="{% url 'ecomapp:customerlogin' %}" class="btn btn-outline-light float-right mt-1 shadow" >Log in</a>
        <a href="{% url 'ecomapp:customerRegistration' %}" class="btn btn-outline-light float-right mr-3  mt-1 shadow" >Register</a>
        {% endif %}
        <div class=" mt-0 ">  
            <span class="col-md-2 mx-auto " >
                <form  action="{% url 'ecomapp:search'  %}" method="GET" >
                    <button class="btn btn-sm btn-outline-light mb-1" >Search </button>
                    <input  class=" btn btn-light btn-sm mb-1  " type="text" name="keyword" placeholder="Tìm sản phẩm.." required   >
                </form>
            </span>       
        </div>
    </div>
</header>
{% if messages %}
		<div class="messages ">
		{% for message in messages %}
            
            {% if message.tags == 'success' %}
            <p id="msg"  class="alert alert-success ">{{ message }}</p>
             {% elif message.tags == 'error' %}
            <p id="msg"  class="alert alert-danger  ">{{ message }}</p>
            {% endif %}

		{% endfor %}
		</div>   
{% endif %}
    <!-- content -->
<body >
    
    {% block content %}
    {% endblock  %}

</body>


<script>
    var alert_info = document.getElementById("msg");
    setTimeout(function() {
        alert_info.style.display = "none";
    }, 3000);
</script>   
  
<!-- footer -->

<footer>
    <div class="row" >
        <div class="col-md-3 col-10  ml-5 mt-3" >
            <span class="text-white " >
                <b>ĐĂNG KÝ NHẬN BẢN TIN TỪ ASICS</b><br><br>
                <b>Trở thành người đầu tiên nhận thông tin về sản phẩm mới, sự kiện độc quyền, ưu đãi trực tuyến.</b><br><br>
                <p>Bằng cách đăng ký, bạn đồng ý nhận các bản tin, email thông tin về sản phẩm, dịch vụ, sự kiện, điện thoại
                     và tin nhắn, cũng như đồng ý với Khoản và Điều Kiện và Chính Sách Quyền Riêng Tư.</p>
                <hr class="bg-white">
                <p>KẾT NỐI VỚI ASICS TẠI</p><br>
                <span>
                    <a href="https://www.facebook.com/asicsvietnamofficial" target="_blank" >
                        <img class="facebook-icon"  src="{% static 'icon/facebook.png' %}"  alt="">
                    </a>
                    <a href="https://www.instagram.com/asicsvn/" target="_blank" >
                        <img class="instagram-icon"  src="{% static 'icon/instagram.png' %}"  alt="">
                    </a>
                </span>
            </span>        
        </div>
        <div class="col-md-2 col-5 ml-5 mt-3 " >
            <span  class="text-white">

                <p>GIỚI THIỆU</p>
                <p class="mb-0" >Về ASICS</p>
                <p class="mb-0" >Điều khoản và Điều kiện</p>
                <p class="mb-0"  >Chính sách Cookie</p>
                <p class="mb-0" >Miễn trừ trách nhiệm</p>
                <p class="mb-0" >Chính sách Quyền Riêng Tư</p>
            </span>

        </div>
        <div class="col-md-2 col-5 mt-3" >
            <div class="text-white" >
                <p>CHĂM SÓC KHÁCH HÀNG</p>
                <p class="mb-0">Liên hệ</p>
                <p class="mb-0">Chính sách đổi trả hàng</p>
                <p class="mb-0">Chính sách giao hàng</p>
                <p class="mb-0">Chính sách thanh toán</p>
                <p class="mb-0">Câu hỏi thường gặp</p>
                <p class="mb-0">Vị trí cửa hàng</p>
                <p class="mb-0">Bảo hành</p>
                <p class="mb-0">Kiểm tra hàng hóa</p>
                <p>Hướng dẫn mua hàng</p>
            </div>
        </div>


        <div class="col-md-2 col-5  mt-3" >
            <div class="text-white" >
                <p>HƯỚNG DẪN KÍCH THƯỚC</p>
                <p class="mb-0">Hướng dẫn kích thước giày</p>
                <p class="mb-0">Hướng dẫn độ rộng giày</p>
                <p class="mb-0">Hướng dẫn độ lệch bàn chân</p>
                <p>Hướng dẫn kích thước áo quần</p>
            </div>    
        </div>
        <div class="col-md-2 col-5 mt-3" >
            <div class="text-white " >
                <p>SẢN PHẨM</p>
                <p class="mb-0">Sản phẩm mới</p>
                <p class="mb-0">Sản phẩm bán chạy</p>
                <p class="mb-0">Sản phẩm độc quyền</p>
                <p class="mb-0">Giày</p>
                <p class="mb-0">Quần áo</p>
                <p class="mb-0">Phụ kiện</p>
                <p>Ưu đãi</p>
            </div>    
        </div>
    </div>
    <div class="row mt-5" >
        <div class="col-md-12 text-white " >
            <div class="ml-5">

                <p>THÔNG TIN VỀ CHỦ TRANG WEB  </p>
                <p>Công ty trách nhiệm hữu hạn ASICS Việt Nam được thành lập theo Giấy chứng nhận đăng ký doanh nghiệp số 0315898690, đăng ký lần đầu ngày 13 tháng 09 năm 2019, thay đổi lần thứ 3 ngày 03 tháng 11 năm 2021 do Phòng Đăng ký kinh doanh, Sở Kế hoạch và Đầu tư Thành phố Hồ Chí Minh cấp.</p>
                <p>Giấy phép kinh doanh số 0315898690-KD0437, cấp lần đầu ngày 7 tháng 11 năm 2019, điều chỉnh lần thứ nhất ngày 5 tháng 4 năm 2021 do Sở Công Thương Thành phố Hồ Chí Minh cấp.</p>
                <p>Giấy phép thành lập cơ sở bán lẻ số 0315898690/KD-0437/03.001, cấp lần đầu ngày 14 tháng 11 năm 2019, gia hạn lần thứ nhất ngày 08 tháng 08 năm 2022 do Sở Công Thương Thành phố Hồ Chí Minh cấp.</p>
                <p class="mb-0">Địa chỉ trụ sở chính: Saigon Centre, Lô L2-26-29, 67 Lê Lợi, Phường Bến Nghé, Quận 1, Thành phố Hồ Chí Minh, Việt Nam.</p>
                <p class="mb-0">Người đại diện theo pháp luật: Ông Gandhi Yogesh</p>
                <p >E-mail: customers-vn@asics.com</p>
            </div>
        </div>
    </div>   
</footer>

<div  class="under-footer" >
    <div class="row ">
        <div class="col-md-6 ml-5 mt-2" >
            <div><b> © 2023 ASICS Vietnam LLC Bảo lưu mọi quyền. </b> </div>
        </div> 
        <div class="col-md-2">

        </div>
        <div class="col-md-3 mt-2 " >
            <div><b><img src="{% static 'images/shoes-logo-new.png' %}" alt=""> Thiết kế sọc trên hai bên giày ASICS® là nhãn hiệu đã đăng ký của Tập đoàn ASICS.</b> </div>
        </div>
    </div>
</div>

</html>

templates/checkout.html
{% extends 'base.html' %}
{% block title %}Check out {% endblock %}
{% load humanize %}
{% block content %}
<div class="container  " >
    <div  class="row " >
        <div class="col-md-7 card-border checkout-item py-2" > 
            <h3>Items in the cart</h3>
            
            <table class="table"  >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Size</th>
                        <th>Sex</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>  
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><img class="img-fluid" style="width:100px;" src="{{cp.product.thumbnail.url}}" alt=""></td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.size}} (US)</td>
                        {% if cp.sex == 'True' %}
                        <td>Nam</td>
                        {% else  %}
                        <td>Nữ</td>
                        {% endif %}
                        <td>{{cp.rate|intcomma}} đ</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal|intcomma}} đ</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="7" class=" text-right" >Total:</th>
                        <th >{{cart.total|intcomma}} đ</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-lg-4 card-border checkout-form ml-4  py-2" >
            <h3>Checkout Form</h3>
            <form action=""  method="POST">
                {% csrf_token  %}  
                {{form.as_p}}  
                <button type="submit" class="btn btn-success">Place Order</button>     
            </form>  

        </div>

    </div>

</div>

{% endblock content %}

templates/contactus.html
{% extends 'base.html' %}
{% block title %} contact us {% endblock %} 
{% block content %}
    <h1>contact us</h1>

{% endblock content %}

templates/customerLogin.html
{% extends 'base.html' %}
{% block title %}Customer Login{% endblock title %}
{%  block content %}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto login-form" >
            <h3>Đăng nhập </h3><hr>
            <form action="" method="POST"  class="mb-3" >
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" >Login as a customer</button>
                {% if error1 %}
                <li style="color:red;" >{{error1}}</li>
                {% endif  %}
            </form>
            <p> Quên mật khẩu? <a href="{% url 'ecomapp:passwordforgot'  %}">Reset lại mật khẩu!</a>  </p>
            <div><span>Chưa có tài khoản ? </span><a href="{% url 'ecomapp:customerRegistration' %}">Đăng kí tại đây!</a></div>

        </div>

    </div>

</div>

{% endblock content %}

templates/customerRegistration.html
{% extends 'base.html' %}
{% block title %}Customer Registration{% endblock title %}
{%  block content %}
<style>
    .errorlist{
        color:red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto register-form" >
            <h3>Đăng kí tài khoản </h3><hr>
            <form action="" method="POST"  class="mb-3" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary" >Đăng kí</button>
            </form>
            <p>Đã có tài khoản ? <a href="{% url 'ecomapp:customerlogin' %}">Login tại đây!</a>  </p>
            <p> Quên mật khẩu ? <a href="{% url 'ecomapp:passwordforgot'  %}">Reset lại mật khẩu!</a>  </p>

        </div>

    </div>

</div>

{% endblock content %}

templates/mycart.html
{% extends 'base.html' %}
{% load humanize %}
{%  block title %}
My cart
{% endblock %}

{% block content %}
<div class="container">
    <div class="row " >
        <div class="col-md-12  card-border mycart py-3" >
            <h4> Items in my cart</h4>
            <table class="table"  >
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Image</th>
                        <th>Product</th>
                        <th>Size</th>
                        <th>Sex</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>   
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr  >
                        <td >{{forloop.counter}}</td>
                        <td>
                            <img  class="img-fluid  " width="100px"  src="{{cp.product.thumbnail.url}}" alt="">
                        </td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.size}} (US)</td>
                        {% if cp.sex == 'True' %}
                        <td>Nam</td>
                        {% else  %}
                        <td>Nữ</td>
                        {% endif %}
                        <td>{{cp.rate|intcomma}} đ</td>
                        <td  >{{cp.quantity}}</td>
                        <td>{{cp.subtotal|intcomma}} đ</td>
                        <td>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=inc" class="btn btn-outline-success">+</a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=dcr" class="btn btn-outline-danger" >-</a>
                            <a href="{% url 'ecomapp:managecart' cp.id %}?action=rmv" class="btn btn-outline-secondary" >x</a>

                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th  colspan="7" class="text-right">Total:</th>
                        <th>{{cart.total|intcomma}} đ</th>
                        {% if cart.cartproduct_set.all %}
                        <th> <a href="{% url 'ecomapp:emptycart' %}" class="btn btn-secondary btn-sm"> Delete all</a> </th>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
            
            {% if cart.cartproduct_set.all %}
            <tr>
                <th>

                    <a href="{% url 'ecomapp:checkout' %}" class="btn btn-success  btn-block btn-lg " >Check out</a>  
                </th>
            </tr>
            
            {% endif %}

        </div>
    </div> 

</div>

{%  endblock %}

templates/passwordreset.html
{%  extends 'base.html' %}
{%  block title  %}Reset password {% endblock %}
{% block content %}
<style>
    .errolist{
        color:red;
    }
</style>

<div class='container' >
    <div class="row" >
        <div class="col-md-8" >
            <form action=""  method="POST" >
                {% csrf_token %}
                {{  form.as_p }}
                <button class="btn btn-success" >Reset password</button>

            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/wishlist.html
{% extends 'base.html' %} 
{% load humanize %} 
{% load static %}
{% block title %} Wish list {% endblock %} 

{% block content %}

<div class="container">
    {% if user.is_authenticated %} 
    <h3 class="mt-3">Danh sách yêu thích</h3>
    {% else %}
    <h3 class="mt-3">Danh sách yêu thích của bạn trống</h3>
    {% endif %}
    <hr>
  <div class="row mt-5">
    {% for p in wishlist.wishlistitem_set.all %}
    <div class="col-md-3 card " >

      <h4 class="mt-3 text-center ">
        <p>{{p.product.title}}</p> 
      </h4>

      <a href="{%  url 'ecomapp:productdetail' p.product.slug %}">
        <img  class="img-fluid  " src="{{p.product.thumbnail.url}}" alt=""  />
      </a>

      <strong>
        <p>Price:
          <small><strike>{{p.product.marked_price|intcomma}}</strike></small>
          {{p.product.selling_price|intcomma}} đ
        </p>
      </strong>

      <div>
        <a href="{% url 'ecomapp:removefromwishlist'  p.id %}" class=" mb-3 btn btn-outline-secondary btn-block">X</a>
      </div>  

    </div>

    {% endfor %}
  </div>

</div>
{% endblock  %}